### PR TITLE
Match trim from gd/imagick

### LINKED ISSUE #44: Certain image/tolerance combinations with Image::trim() fail
## Describe the bug

Errors occur for certain image/tolerance combinations with `TrimModifier::Class`.

For example, the code in the example throws an error from tolerance 20 for the source image given below.

> Fatal error: Uncaught Jcupitt\Vips\Exception: libvips error: jpegload: no property named `n' extract_area: bad extract area

## Code Example

```php
use Intervention\Image\Drivers\Vips\Driver as VipsDriver;
use Intervention\Image\ImageManager;

$image = ImageManager::withDriver(VipsDriver::class)
    ->read('apple.jpg')
    ->trim(20);
```

## Expected behavior

Ideally, the modifier should behave in the same way as its counterparts for GD and Imagick(see below).

### Source Image
aaa

### Result with Imagick's `TrimModifier::Class`

localhost

## Environment
 - PHP Version: PHP 8.4
 - OS: macOS 14
 - Intervention Image Version: 3.10.2
 - php-vips Version: develop
 - libvips Version: 8.16.0

### PR DESCRIPTION
**Pull request by deluxetom**
* resolves #44 

result image:
trimmed-apple

### CODE REVIEW

File: src/Modifiers/TrimModifier.php [hunk 1]
```diff
@@ -34,23 +34,20 @@ public function apply(ImageInterface $image): ImageInterface
...
 
         $maxThreshold = match ($image->core()->native()->format) {
-            BandFormat::UCHAR => 255,
             BandFormat::USHORT => 65535,
             BandFormat::FLOAT => 1,
             default => 255,
         };
 
         foreach ($points as $point) {
-            unset($point[3]); // remove alpha
```
Comment (deluxetom) [inline src/Modifiers/TrimModifier.php:44]: image is already flattened, by default:
https://www.libvips.org/API/current/libvips-arithmetic.html#vips-find-trim

**Comment by olivervogel** [comment]
Wonderful!
