### PR TITLE
Check driver health by using libvips implementation

### LINKED ISSUE #69: Exception on no libvips
## Describe the bug
There is no exception if no `libvips` installed.

## Code Example
```php
use Intervention\Image\Drivers\Vips\Driver as VipsDriver;

// checkHealth in __contruct should throw an exception
new VipsDriver();
```

## Expected behavior
`checkHealth` should throw an exception when no `libvips` installed. Maybe `checkHealth` should check version through `Jcupitt\Vips\FFI::version()` and catch `Jcupitt\Vips\Exception`, as health checks already [implemented by php-vips](https://github.com/libvips/php-vips/blob/256575d7c5247d4fb3e98bf10ab1e10a571684c7/src/FFI.php#L239)?

## Environment:
 - PHP Version: 8.1.27
 - OS: Debian 12
 - Intervention Image Version: 3.11.0
 - php-vips Version: 2.4.1
 - libvips Version: N/A

### PR DESCRIPTION
**Pull request by olivervogel**
Resolves #69

### CODE REVIEW

File: src/Driver.php [hunk 1]
```diff
@@ -181,15 +181,15 @@ public function supports(string|Format|FileExtension|MediaType $identifier): boo
...
     public function checkHealth(): void
     {
-        if (!extension_loaded('ffi') && !extension_loaded('vips')) {
+        try {
+            // check health by calling Jcupitt\Vips\FFI::init()
+            VipsConfig::version();
+        } catch (VipsException $e) {
             throw new DriverException(
-                'PHP extension FFI or VIPS must be enabled to use this driver.'
+                'libvips does not seem to be installed or not correctly configured.',
```
Comment (deluxetom) [inline src/Driver.php:189]:
```suggestion
                'libvips does not seem to be installed correctly.',
```

File: src/Driver.php [hunk 2]
```diff
@@ -181,15 +181,15 @@ public function supports(string|Format|FileExtension|MediaType $identifier): boo
...
+                previous: $e
             );
         }
-
-        if (version_compare(PHP_VERSION, '8.3', '>=') && ini_get('zend.max_allowed_stack_size') != '-1') {
-            throw new DriverException("zend.max_allowed_stack_size not set to '-1'");
-        }
```
Comment (deluxetom) [inline src/Driver.php:192]: does it get checked in `VipsConfig`?

**Review by deluxetom — APPROVED** [review]
looks great!

File: src/Driver.php (hunk 2 above)
Comment (olivervogel) [reply src/Driver.php:192]: Almost  exactly the same: https://github.com/libvips/php-vips/blob/master/src/FFI.php#L246-L249
